env:
  num_drones: 10 # ドローンの数
  camera_width: 640 # カメラ画像の幅
  camera_height: 360 # カメラ画像の高さ
  goal_horizon: 8 
  sencing_radius: 3 
  frequency: 100 # シミュレーションの周波数
  max_vel: 3.0
  map_name: "agents3_28703135"
  start_pos: [0.0, 0.0, 0.0]
  goal_pos: [0.0, 0.0, 0.0]
vae:
  batch_size: 100 # バッチサイズ
  image_size: [128, 128] # 画像サイズ
  hidden_dims: [32, 64, 128, 256, 512] # 隠れ層の次元数
  latent_dim: 200 # 潜在変数の次元数
  in_channels: 1 # 入力画像のチャンネル数(デプス画像は1)
  lr: 0.005 # 学習率
  scheduler_gamma: 0.95 # 学習率の減衰率
  weight_decay: 0.0 # 重み減衰
  kld_weight: 0.05 # KLダイバージェンスの重み
  manual_seed: 42 # 乱数シード
deepset:
  latent_dim: 16 # 潜在変数の次元数
ppo:
  batch_size: 100 # バッチサイズ
  scheduler_gamma: 0.95 # 学習率の減衰率