algo: "WDAIL"
env:
  name: "DotEnv" # 環境の名前
  num_drones: 10 # ドローンの数
  camera_width: 640 # カメラ画像の幅
  camera_height: 360 # カメラ画像の高さ
  goal_horizon: 8 
  sencing_radius: 3
  drone_radius: 0.2
  frequency: 100 # シミュレーションの周波数
  max_vel: 3.0
  map_name: "agents10_57097467"
  start_pos: [0.0, 0.0, 0.0]
  goal_pos: [0.0, 0.0, 0.0]
  state_dim: 6 # 状態の次元数
  action_dim: 5 # 行動の次元数
wdail:
  use_gail: true # GAILを使うかどうか
  total_steps: 1000000 # 学習ステップ数
  update_steps: 2048 # バッチ数
  gail_batch_size: 128 # GAILのバッチサイズ
  num_mini_batch: 32 # ミニバッチサイズ
  use_linear_lr_decay: true # 線形減衰を使うかどうか
  lr: 0.0003 # 学習率
  eps: 0.00001 # ε
  gail_epoch: 5 # GAILのエポック数
  gail_threshold: 10 # GAILの閾値
  gail_pre_epoch: 100 # GAILの事前学習エポック数
  gamma: 0.99 # 割引率
  use_gae: true # GAEを使うかどうか
  gae_lambda: 0.95 # GAEのλ
  use_proper_time_limits: true # Proper Time Limitsを使うかどうか
  num_processes: 1 # プロセス数
  data_size: 100000 # データセットのサイズ
  log_interval: 1 # ログのインターバル
discriminator:
  cliprew_down: -10 # 報酬の下限
  cliprew_up: 10 # 報酬の上限
  reward_type: 0 # 報酬の種類
  update_rms: false # RMSPropを使うかどうか
  hidden_dim: 100 # 隠れ層の次元数
vae:
  batch_size: 100 # バッチサイズ
  image_size: [128, 128] # 画像サイズ
  hidden_dims: [32, 64, 128, 256, 512] # 隠れ層の次元数
  latent_dim: 64 # 潜在変数の次元数
  in_channels: 1 # 入力画像のチャンネル数(デプス画像は1)
  lr: 0.005 # 学習率
  scheduler_gamma: 0.95 # 学習率の減衰率
  weight_decay: 0.0 # 重み減衰
  kld_weight: 0.05 # KLダイバージェンスの重み
  manual_seed: 42 # 乱数シード
deepset:
  latent_dim: 16 # 潜在変数の次元数
ppo:
  ppo_epoch: 10 # PPOのエポック数
  batch_size: 100 # バッチサイズ
  scheduler_gamma: 0.95 # 学習率の減衰率
  hidden_size: 64 # 隠れ層の次元数
  max_grad_norm: 0.5 # 最大勾配ノルム
  value_loss_coef: 0.5 # 値関数の損失係数
  entropy_coef: 0.01 # エントロピー係数
  clip_param: 0.2 # クリップするパラメータ